# GitHub Pages configuration
# Disable Jekyll processing for static site
safe: true
include: []
exclude: []
keep_files: []

# Disable Jekyll plugins
plugins: []

# Exclude files from processing
exclude:
  - README.md
  - .gitignore
  - .git/
  - node_modules/
  - package.json
  - package-lock.json
  - .vercelignore
  - vercel.json
  - next.config.js
  - public/

# Include files
include:
  - _redirects

# Site settings
title: Zura Projects
description: M.P. Projects – Renovation at Its Best
url: https://michael2001papis.github.io
baseurl: /Zura-1.5

# Vercel settings
vercel:
  name: zura-projects
  version: 2

# Build settings
markdown: kramdown
highlighter: rouge
